apiVersion: v1
kind: Service
metadata:
  name: hello-world-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hello-world
  ports:
    - port: 9113
      targetPort: 9113
      name: metrics