apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: hello-world
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http